### ISSUE TITLE
App is not showing any elements when starting

### ISSUE THREAD

**Issue by alexbauerde** [GuillaumeBiton/hackernews7-svelte#1]
Hello,

i've just cloned the master and run npm install.

npm run dev and npm start is both not working, the page will stay white and got several errors in the console:

![image](https://user-images.githubusercontent.com/16516990/105465459-3a1f2680-5c93-11eb-8efa-3917f6e4f5dd.png)

Do you have any suggestions how to fix that? Thanks a lot !

**Comment by GuillaumeBiton** [comment]
Hi,

interesting. Which plateform did you use ?

**Comment by alexbauerde** [comment]
Hi @GuillaumeBiton 

Windows10 Pro
NodeJS 12.18.2
npm 6.14.5

Just updated NodeJS to 14.15.4 and its still not working

**Comment by GuillaumeBiton** [comment]
Hi sorry for the wait.

Ubuntu 20.10
NodeJS 12.18.1
NPM 6.14.8

I have an issue with gh-pages but locally it works

**Comment by ulranh** [comment]
Archlinux
node v15.8.0
npm 6.14.11

Works for me with firefox but not with chrome.

**Comment by GuillaumeBiton** [comment]
OK rebuild it using framework7-cli and now gh-pages works.
